google.client.id=82875852499-en92hgicdr86c3tpjkisen2kngsu254k.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:8888/callback
google.scope=ahd.benabdallah@esprit.tn